### PR TITLE
Networks

### PR DESCRIPTION
**Pull request by robbiecarlton**

### CODE REVIEW

**Comment by levity** [comment]
looking good so far -- i like how the reducers set up a toggle between community and network without having to introduce setCurrentNetworkId anywhere new

**Comment by robbiecarlton** [comment]
thanks, I liked that part too :)

**Comment by robbiecarlton** [comment]
screen shot 2016-05-19 at 10 17 08 pm
screen shot 2016-05-19 at 10 17 28 pm
screen shot 2016-05-19 at 10 20 16 pm
screen shot 2016-05-19 at 10 20 40 pm
screen shot 2016-05-19 at 10 32 24 pm

**Comment by robbiecarlton** [comment]
@levity - I haven't figured out how to display the network name in the left nav in a way that looks good. 
Also, just used random icons for the network, and communities page. I'm sure Damian will want to change them.
Other than those things, it's all here and working.

**Comment by levity** [comment]
sweet -- definitely could use a design pass, but for now:
- is there an icon that is more like a tree, for the network menu item?
  maybe even a share icon like this:
  https://cdn3.iconfinder.com/data/icons/glypho-free/64/share-128.png
- you could also just say "Network" instead of the network name in the left
  nav
- adjust the positioning of the network name and the line below it that
  says "Network" in the communities dropdown toggle button so that
  collectively they're vertically aligned with the icon

then :shipit:

**Comment by edwardwest** [comment]
Looks great guys!

Thanks for putting that together so quickly.

Love you

**Comment by robbiecarlton** [comment]
Will have to get an icon like that from Ed, I don't have anything in the
font.
Re the topnav, I merged, will you take a look at the alignment in context.
Specifically clicking between networks and communities. I think this
alignment makes more sense (the name is the same height with both)
If you still want it changed after seeing it in action let me know.

On Friday, May 20, 2016, edwardwest notifications@github.com wrote:

> Looks great guys!
> 
> Thanks for putting that together so quickly.
> 
> Love you
> 
> On Fri, May 20, 2016 at 3:55 PM, Lawrence Wang <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > sweet -- definitely could use a design pass, but for now:
> > - is there an icon that is more like a tree, for the network menu item?
> >   maybe even a share icon like this:
> >   https://cdn3.iconfinder.com/data/icons/glypho-free/64/share-128.png
> > - you could also just say "Network" instead of the network name in the
> >   left
> >   nav
> > - adjust the positioning of the network name and the line below it that
> >   says "Network" in the communities dropdown toggle button so that
> >   collectively they're vertically aligned with the icon
> > 
> > then :shipit:
> > 
> > On Thu, May 19, 2016 at 10:35 PM Robbie Carlton <
> > notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> > 
> > > @levity https://github.com/levity - I haven't figured out how to
> > > display the network name in the left nav in a way that looks good.
> > > Also, just used random icons for the network, and communities page. I'm
> > > sure Damian will want to change them.
> > > Other than those things, it's all here and working.
> > > 
> > > —
> > > You are receiving this because you were mentioned.
> > > 
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/Hylozoic/hylo-redux/pull/55#issuecomment-220521266
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/Hylozoic/hylo-redux/pull/55#issuecomment-220737326
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Hylozoic/hylo-redux/pull/55#issuecomment-220756247

##

**Comment by edwardwest** [comment]
Just checked it out-- seems like it works great save for that members
doesn't load for me:

https://www.evernote.com/shard/s130/sh/ece87d9f-a17a-45e6-903c-8bacac2b4cce/e8ce9df684049c3c83d2e0b63c2898ab/deep/0/(5)-Hylo.png

---

_Edward West_
mobile 415.225.7335
Facebook http://www.facebook.com/edwardjwest  Twitter
http://www.twitter.com/edwardwest  LinkedIn
http://www.linkedin.com/in/edwardwest

**Comment by levity** [comment]
i just got a rollbar report about this and fixed it. it was a typo that
occurred when the PR was merged

**Pull request merged**
