### PR TITLE
Add location to post

### PR DESCRIPTION
**Pull request by robbiecarlton**
I ended up starting with the location field in events

### CODE REVIEW

**Comment by robbiecarlton** [comment]
screen shot 2015-12-03 at 2 32 06 pm
@levity can I merge?

**Comment by levity** [comment]
it has conflicts.
can you reduce the margin after the text input by, um, 5px? it should match the spacing between the title and the 'DETAILS' header

**Comment by robbiecarlton** [comment]
it didn't have conflicts when I posted :P
will fix and the spacing

**Comment by robbiecarlton** [comment]
@levity fixed, ok to merge?

**Comment by levity** [comment]
:+1:

**Pull request merged**
