### PR TITLE
Updated Invite Page

### PR DESCRIPTION
**Pull request by robbiecarlton**

### CODE REVIEW

**Comment by robbiecarlton** [comment]
screen shot 2016-10-23 at 7 29 01 pm
screen shot 2016-10-23 at 7 29 18 pm
screen shot 2016-10-23 at 7 29 26 pm

**Comment by robbiecarlton** [comment]
The design was missing a few elements (see task https://app.asana.com/0/17131836607372/99753459901192) so I just made up the gaps.

**Comment by robbiecarlton** [comment]
depends on https://github.com/Hylozoic/hylo-node/pull/182

**Comment by robbiecarlton** [comment]
🎊

**Comment by levity** [comment]
Omit the "Resend" and "Approve" column headers. Otherwise I think we're good

**Pull request merged**
