### PR TITLE
Browse topics limit

### PR DESCRIPTION
**Pull request by robbiecarlton**
screen shot 2016-10-18 at 2 32 39 pm

### CODE REVIEW

**Comment by robbiecarlton** [comment]
depends on https://github.com/Hylozoic/hylo-node/pull/181

**Comment by robbiecarlton** [comment]
@levity - good to merge?

**Comment by levity** [comment]
I think we can just have the "Show more" link inline with the rest of the meta text. No need to distract from the main calls to action.

**Comment by levity** [comment]
(Unless Damian specifically requested it that way, in which case just make the button text and border color consistent.) Otherwise, :cool:

**Pull request merged**
