### PR TITLE
Is typing message improvements

### PR DESCRIPTION
**Pull request by Connoropolous**
**before**
screen shot 2017-01-05 at 4 04 15 pm

**after**
screen shot 2017-01-05 at 4 03 26 pm

**before**

screen shot 2017-01-05 at 3 27 38 pm

**after**

screen shot 2017-01-05 at 3 56 59 pm

### CODE REVIEW

**Comment by levity** [comment]
interesting -- the white border that cuts off the message text and "New Messages" button looks kind of off to me -- want to run this by Alex?

**Comment by Connoropolous** [comment]
that's when you're scrolled up... yeah I can ask Alex. We could just refrain from showing the message when you're scrolled up. I thought the border also looked cheesy, at least when you're scrolled all the way to the bottom. maybe the solution is showing the border when you've scrolled up

**Comment by Connoropolous** [comment]
you can see what it looks like normally, if you're at the bottom, in the second screenshot

**Comment by Connoropolous** [comment]
I tried doing as Robbie suggested and just 'squeezing it in', but I guess this is why, after everything, slack squeezed it in underneath the message input

**Pull request merged**
