### PR TITLE
give better closure to the invitation process

### PR DESCRIPTION
**Pull request by Connoropolous**
screen shot 2017-01-27 at 5 30 10 pm

### CODE REVIEW

**Comment by levity** [comment]
Hmm -- this goes in the direction of making the modal single-use. If that's the case, which I'm ok with, we could just close it entirely after success and show the success message with Notifier.

**Comment by Connoropolous** [comment]
what if I re-enabled it to cancel&invite if you edited the list again?

**Comment by Connoropolous** [comment]
and maybe clear the list too? so they're less likely to fire off duplicates?

**Comment by levity** [comment]
sure, that could work too.

**Comment by Connoropolous** [comment]
I'm just going to drop this, it will be made irrelevant before long

**Pull request closed without merging**
