### PR TITLE
Post editor design changes

### PR DESCRIPTION
**Pull request by robbiecarlton**
screen shot 2016-08-24 at 3 28 41 pm

screen shot 2016-08-24 at 3 28 49 pm

screen shot 2016-08-24 at 3 28 58 pm

### CODE REVIEW

**Comment by robbiecarlton** [comment]
@levity - good to merge?

**Comment by levity** [comment]
- should be vertically centered in its border

**Comment by levity** [comment]
i think you should push the icons in the dropdowns a little to the left too

**Comment by robbiecarlton** [comment]
screen shot 2016-08-25 at 4 40 16 pm
screen shot 2016-08-25 at 4 40 10 pm

**Comment by levity** [comment]
:+1:

**Pull request merged**
