### PR TITLE
Cl onboarding revisions

### PR DESCRIPTION
**Pull request by robbiecarlton**
I'm still working on the new modals, but wanted to push all these fixes to improve the experience on the site.

### CODE REVIEW

**Comment by robbiecarlton** [comment]
@levity - good to merge?

**Comment by levity** [comment]
can i get a screenshot of the checklist modal over the community page?

**Comment by robbiecarlton** [comment]
screen shot 2016-09-29 at 5 53 41 pm

**Comment by levity** [comment]
sweet, :shipit:

**Pull request merged**
