### PR TITLE
Complete Request mobile layout fixes

### PR DESCRIPTION
**Pull request by lorenjohnson**

### CODE REVIEW

**Review by levity — COMMENTED** [review]
for front-end changes like this, can you append a screenshot?

**Comment by lorenjohnson** [comment]
Yup, to start here is a before screenshot: 
image

and the after fix:

image

**Comment by lorenjohnson** [comment]
Also, the wrapping applies in the case of the completed contributors heading and the linked contributor name was made bold (which had been missed in previous version): 

image

**Review by levity — APPROVED** [review]
lgtm!

**Pull request merged**
